version: "3.9"

services:
  database:
    container_name: postgres
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: "api"
      POSTGRES_USER: "web"
      POSTGRES_PASSWORD: "web"
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "54321:5432"
